#!/usr/bin/env python3
"""Materialize the canonical ABIs for npm and Cargo packaging."""

import argparse
import json
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
evm = Path(__file__).resolve().parents[1]
generated = {}
typescript = '// Generated by evm/scripts/sync-abis.py. Edit evm/abi instead.\n'
typescript += 'import { type Abi } from "viem";\n\n'
for name in ("SwigConfig", "SwigConfigFactory", "SwigVault", "SwigCapsule"):
    raw = (evm / "abi" / f"{name}.json").read_bytes()
    abi = json.loads(raw)
    generated[evm / "rust" / "abi" / f"{name}.json"] = raw
    export = name[0].lower() + name[1:] + "Abi"
    typescript += f"export const {export} = {json.dumps(abi, indent=2)} as const satisfies Abi;\n\n"
generated[evm / "typescript" / "src" / "abi.ts"] = (typescript.rstrip() + "\n").encode()

for path, content in generated.items():
    if args.check:
        if not path.exists() or path.read_bytes() != content:
            raise SystemExit(f"Outdated generated ABI: {path.relative_to(evm)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
print("ABI package files are current" if args.check else "Generated ABI package files")
