[package]
name = "swig-interface"
version.workspace = true
edition = "2021"
license = "AGPL-3.0"
description = "Solana program for the Swig protocol"
publish = false
authors.workspace = true
documentation.workspace = true
repository = "https://github.com/anagrambuild/swig-protocol-sdk"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
solana-sdk = { version = "4.0.1" }
solana-system-interface = "3.1.0"
swig = { git = "https://github.com/anagrambuild/swig-wallet.git", rev = "eefb531bc7649313d2d9951efe2030775466ca11", default-features = false, features = [
    "no-entrypoint",
] }
swig-compact-instructions = { git = "https://github.com/anagrambuild/swig-wallet.git", rev = "eefb531bc7649313d2d9951efe2030775466ca11", default-features = false, features = [
    "client",
] }
swig-state = { git = "https://github.com/anagrambuild/swig-wallet.git", rev = "eefb531bc7649313d2d9951efe2030775466ca11" }
anyhow = "1.0.75"
solana-secp256r1-program = "3.0.0"
